baseurl = "http://blog.publysher.nl/"
languageCode = "en-us"
title = "Publysher Development Blog"
disqusShortname = "publysher-blog"
theme = "hyde-x"

PygmentsStyle = "tango"

[author]
	name = "Publysher"

[params]
	github = "https://github.com/publysher"
	linkedin = "https://www.linkedin.com/in/yduppen"

	theme = "theme-base-08"

	tagline = "Development"

	googleAuthorship = "111509161421737611843"
	googleAnalytics = "UA-24629686-1"

