baseurl = "http://blog.n3g.gs/"
languageCode = "en-uk"
title = "neg.gs Development Blog"
disqusShortname = "neg.gs-blog"
theme = "hyde-x"

PygmentsStyle = "tango"

[author]
	name = "neg.gs"

[params]
	github = "https://github.com/neggs"
	linkedin = "#"

	theme = "theme-base-08"

	tagline = "Development"

	googleAuthorship = "#"
	googleAnalytics = "#"

